version: 'DOCKER_COMPOSER_VERSION'

volumes:
  mysql:
    driver: local

networks:
  sandbox:
    driver: bridge

services:
  php:
    env_file:
      - .env
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - ${PHP_APACHE_PORT}:80
    networks:
      - sandbox

  postgres:
    image: postgres:12.1
    restart: always
    ports:
    - ${POSTGRESS_PORTS}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRESS_DB}

  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - ${ADMINER_PORTS}:8080
    environment:
      PMA_HOST: mysql
    networks:
      - sandbox
